# Read tables generated by CLIP.py
ago <-read.table('AGO_annotated_.txt', as.is = T, header = T)
fus1 <-read.table('FUS_Rep1_annotated_.txt', as.is = T, header = T)
fus2 <-read.table('FUS_Rep2_annotated_.txt', as.is = T, header = T)
fus3 <-read.table('FUS_Rep3_annotated_.txt', as.is = T, header = T)
mbnl1 <-read.table('Mbnl1_Rep1_annotated_.txt', as.is = T, header = T)
mbnl1.2 <-read.table('Mbnl1_Rep2_annotated_.txt', as.is = T, header = T)
mbnl2 <-read.table('Mbnl2_annotated_.txt', as.is = T, header = T)
elav <-read.table('nElavl_annotated_.txt', as.is = T, header = T)
ptbp2 <-read.table('Ptbp2_annotated_.txt', as.is = T, header = T)
td43 <-read.table('TD43_annotated_.txt', as.is = T, header = T)
rbfox1 <- read.table('Rbfox1CLIP_clipper_annotated_utr_cds.bed', as.is = T, header = T)
rbfox2<- read.table('Rbfox2_CLIP_seq_clipper_annotated_utr_cds.bed', as.is = T, header = T)


# generate subsets

# silac target genes
rbfox2_silac<-merge(silac, rbfox2, by.x = 'Gene.Symbols', by.y = 'gene_name' )
rbfox1_silac<-merge(silac, rbfox1, by.x = 'Gene.Symbols', by.y = 'gene_name' )
rbfox1_silac<-data.frame("chr"= rbfox1_silac[,7], "start"= rbfox1_silac[,8], "end" = rbfox1_silac[,9], "cluster"= rbfox1_silac[,10], "score" = rbfox1_silac[,14], "strand" = NA,"gene"= rbfox1_silac[,1], "region"= rbfox1_silac[,13], "silac_id"= rbfox1_silac[,2],"silac_FC"= rbfox1_silac[,3])
rbfox2_silac<-data.frame("chr"= rbfox2_silac[,7], "start"= rbfox2_silac[,8], "end" = rbfox2_silac[,9], "cluster"= rbfox2_silac[,10], "score" = rbfox2_silac[,14], "strand" = NA,"gene"= rbfox2_silac[,1], "region"= rbfox2_silac[,13], "silac_id"= rbfox2_silac[,2],"silac_FC"= rbfox2_silac[,3])
ago_silac <- subset(ago,silac_id!='NA')
fus1_silac <- subset(fus1,silac_id!='NA')
fus2_silac <- subset(fus2,silac_id!='NA')
fus3_silac <- subset(fus3,silac_id!='NA')
mbnl1_silac <- subset(mbnl1,silac_id!='NA')
mbnl1.2_silac <- subset(mbnl1.2,silac_id!='NA')
mbnl2_silac <- subset(mbnl2,silac_id!='NA')
elav_silac <- subset(elav,silac_id!='NA')
ptbp2_silac <- subset(ptbp2,silac_id!='NA')
td43_silac <- subset(td43,silac_id!='NA')


# generate region subsets
# UTR3
ago_utr3 = subset(ago_silac, region == 'utr3')
fus1_utr3 = subset(fus1_silac, region == 'utr3')
fus2_utr3 = subset(fus2_silac, region == 'utr3')
fus3_utr3 = subset(fus3_silac, region == 'utr3')
mbnl1_utr3 = subset(mbnl1_silac, region == 'utr3')
mbnl1.2_utr3 = subset(mbnl1.2_silac, region == 'utr3')
mbnl2_utr3 = subset(mbnl2_silac, region == 'utr3')
elav_utr3 = subset(elav_silac, region == 'utr3')
ptbp2_utr3 = subset(ptbp2_silac, region == 'utr3')
td43_utr3 = subset(td43_silac, region == 'utr3')
rbfox1_utr3 = subset(rbfox1_silac, region == 'utr3')
rbfox2_utr3 = subset(rbfox2_silac, region == 'utr3')

# UTR5
ago_utr5 = subset(ago_silac, region == 'utr5')
fus1_utr5 = subset(fus1_silac, region == 'utr5')
fus2_utr5 = subset(fus2_silac, region == 'utr5')
fus3_utr5 = subset(fus3_silac, region == 'utr5')
mbnl1_utr5 = subset(mbnl1_silac, region == 'utr5')
mbnl1.2_utr5 = subset(mbnl1.2_silac, region == 'utr5')
mbnl2_utr5 = subset(mbnl2_silac, region == 'utr5')
elav_utr5 = subset(elav_silac, region == 'utr5')
ptbp2_utr5 = subset(ptbp2_silac, region == 'utr5')
td43_utr5 = subset(td43_silac, region == 'utr5')
rbfox1_utr5 = subset(rbfox1_silac, region == 'utr5')
rbfox2_utr5 = subset(rbfox2_silac, region == 'utr5')


# CDS
ago_cds = subset(ago_silac, region == 'cds')
fus1_cds = subset(fus1_silac, region == 'cds')
fus2_cds = subset(fus2_silac, region == 'cds')
fus3_cds = subset(fus3_silac, region == 'cds')
mbnl1_cds = subset(mbnl1_silac, region == 'cds')
mbnl1.2_cds = subset(mbnl1.2_silac, region == 'cds')
mbnl2_cds = subset(mbnl2_silac, region == 'cds')
elav_cds = subset(elav_silac, region == 'cds')
ptbp2_cds = subset(ptbp2_silac, region == 'cds')
td43_cds = subset(td43_silac, region == 'cds')
rbfox1_cds = subset(rbfox1_silac, region == 'cds')
rbfox2_cds = subset(rbfox2_silac, region == 'cds')



# merge all RBP hit tables

# Silac target genes
total = merge(as.data.frame(table(ago_silac$gene)), as.data.frame(table(fus1_silac$gene)), by = 'Var1', all = T)
total = merge(total,as.data.frame(table(fus2_silac$gene)),  by = 'Var1', all = T)
names(total)<- c('Var1', 'Ago', 'Fus.rep1', 'Fus.rep2')
N = names(total)
total = merge(total,as.data.frame(table(fus3_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Fus.rep3')
N = names(total)
total = merge(total,as.data.frame(table(mbnl1_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Mbnl1.rep1')
N = names(total)
total = merge(total,as.data.frame(table(mbnl1.2_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Mbnl1.rep2')
N = names(total)
total = merge(total,as.data.frame(table(mbnl2_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Mbnl2')
N = names(total)
total = merge(total,as.data.frame(table(elav_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'nElavl')
N = names(total)
total = merge(total,as.data.frame(table(ptbp2_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Ptbp2')
N = names(total)
total = merge(total,as.data.frame(table(td43_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'TD43')
N = names(total)
total = merge(total,as.data.frame(table(rbfox1_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Rbfox1')
N = names(total)
total = merge(total,as.data.frame(table(rbfox2_silac$gene)),  by = 'Var1', all = T)
names(total)<- c(N, 'Rbfox2')
total[total==0]<- NA

# UTR3
total_utr3 = merge(as.data.frame(table(ago_utr3$gene)), as.data.frame(table(fus1_utr3$gene)), by = 'Var1', all = T)
total_utr3 = merge(total_utr3,as.data.frame(table(fus2_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c('Var1', 'Ago', 'Fus.rep1', 'Fus.rep2')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(fus3_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Fus.rep3')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(mbnl1_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Mbnl1.rep1')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(mbnl1.2_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Mbnl1.rep2')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(mbnl2_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Mbnl2')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(elav_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'nElavl')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(ptbp2_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Ptbp2')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(td43_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'TD43')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(rbfox1_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Rbfox1')
N = names(total_utr3)
total_utr3 = merge(total_utr3,as.data.frame(table(rbfox2_utr3$gene)),  by = 'Var1', all = T)
names(total_utr3)<- c(N, 'Rbfox2')
total_utr3[total_utr3==0]<- NA


# UTR5
total_utr5 = merge(as.data.frame(table(ago_utr5$gene)), as.data.frame(table(fus1_utr5$gene)), by = 'Var1', all = T)
total_utr5 = merge(total_utr5,as.data.frame(table(fus2_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c('Var1', 'Ago', 'Fus.rep1', 'Fus.rep2')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(fus3_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Fus.rep3')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(mbnl1_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Mbnl1.rep1')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(mbnl1.2_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Mbnl1.rep2')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(mbnl2_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Mbnl2')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(elav_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'nElavl')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(ptbp2_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Ptbp2')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(td43_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'TD43')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(rbfox1_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Rbfox1')
N = names(total_utr5)
total_utr5 = merge(total_utr5,as.data.frame(table(rbfox2_utr5$gene)),  by = 'Var1', all = T)
names(total_utr5)<- c(N, 'Rbfox2')
total_utr5[total_utr5==0]<- NA

# CDS
total_cds = merge(as.data.frame(table(ago_cds$gene)), as.data.frame(table(fus1_cds$gene)), by = 'Var1', all = T)
total_cds = merge(total_cds,as.data.frame(table(fus2_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c('Var1', 'Ago', 'Fus.rep1', 'Fus.rep2')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(fus3_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Fus.rep3')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(mbnl1_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Mbnl1.rep1')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(mbnl1.2_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Mbnl1.rep2')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(mbnl2_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Mbnl2')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(elav_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'nElavl')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(ptbp2_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Ptbp2')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(td43_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'TD43')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(rbfox1_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Rbfox1')
N = names(total_cds)
total_cds = merge(total_cds,as.data.frame(table(rbfox2_cds$gene)),  by = 'Var1', all = T)
names(total_cds)<- c(N, 'Rbfox2')
total_cds[total_cds==0]<- NA


# read in length file
region_length = read.table('silac_region_length.txt', as.is = T, header = T)
genes = names(table(region_length$gene))

mean_region_length = NULL
for(i in 1:length(genes)){
  x = subset(region_length, gene == genes[i])
  means = colMeans(x[2:4])
  mean_region_length = rbind(mean_region_length, c(genes[i], means))
}
mean_region_length = as.data.frame(mean_region_length)
names(mean_region_length) <- c('gene', 'cds', 'utr3', 'utr5')

# merge with previous tables
silac = read.table('silac.txt', as.is = T, header = T, sep = '\t')
silac_FC = silac[,1:3]
silac_FC = merge(silac_FC, mean_region_length, by.x = 'Gene.Symbols', by.y = 'gene', all = T)
silac_total = merge(silac_FC, total, by.x = 'Gene.Symbols', by.y = 'Var1', all = T)
silac_utr3 = merge(silac_FC, total_utr3, by.x = 'Gene.Symbols', by.y = 'Var1', all = T)
silac_utr5 = merge(silac_FC, total_utr5, by.x = 'Gene.Symbols', by.y = 'Var1', all = T)
silac_cds = merge(silac_FC, total_cds, by.x = 'Gene.Symbols', by.y = 'Var1', all = T)


# normalize by genelength
utr3_norm = silac_utr3[,7:18]/as.numeric(as.character(silac_utr3$utr3))
utr3_norm = cbind(silac_utr3[,1:3], utr3_norm)

utr5_norm = silac_utr5[,7:18]/as.numeric(as.character(silac_utr5$utr5))
utr5_norm = cbind(silac_utr5[,1:3], utr5_norm)

cds_norm = silac_cds[,7:18]/as.numeric(as.character(silac_cds$cds))
cds_norm = cbind(silac_cds[,1:3], cds_norm)

total_norm = silac_total[,7:18]/(as.numeric(as.character(silac_total$cds))+as.numeric(as.character(silac_total$utr3))+as.numeric(as.character(silac_total$utr5)))
total_norm = cbind(silac_total[,1:3], total_norm)

# devide into tables up and down regulated genes
plus_total = subset(silac_total,PTX.Contr..fold. > 0 )
plus_cds = subset(silac_cds,PTX.Contr..fold. > 0 )
plus_utr3 = subset(silac_utr3,PTX.Contr..fold. > 0 )
plus_utr5 = subset(silac_utr5,PTX.Contr..fold. > 0 )

minus_total = subset(silac_total,PTX.Contr..fold. < 0 )
minus_cds = subset(silac_cds,PTX.Contr..fold. < 0 )
minus_utr3 = subset(silac_utr3,PTX.Contr..fold. < 0 )
minus_utr5 = subset(silac_utr5,PTX.Contr..fold. < 0 )

plus_total_norm = subset(total_norm,PTX.Contr..fold. > 0 )
plus_cds_norm = subset(cds_norm,PTX.Contr..fold. > 0 )
plus_utr3_norm = subset(utr3_norm,PTX.Contr..fold. > 0 )
plus_utr5_norm = subset(utr5_norm,PTX.Contr..fold. > 0 )

minus_total_norm = subset(total_norm,PTX.Contr..fold. < 0 )
minus_cds_norm = subset(cds_norm,PTX.Contr..fold. < 0 )
minus_utr3_norm = subset(utr3_norm,PTX.Contr..fold. < 0 )
minus_utr5_norm = subset(utr5_norm,PTX.Contr..fold. < 0 )


# length distribution
total_length_plus = as.numeric(as.character(plus_total[,4]))+as.numeric(as.character(plus_total[,5]))+as.numeric(as.character(plus_total[,6]))
total_length_minus = as.numeric(as.character(minus_total[,4]))+as.numeric(as.character(minus_total[,5]))+as.numeric(as.character(minus_total[,6]))

# UTR3
# significant change between groups (normalized by length)
Ago = wilcox.test(plus_utr3_norm$Ago, minus_utr3_norm$Ago, paired = F)
Fus1 = wilcox.test(plus_utr3_norm$Fus.rep1, minus_utr3_norm$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_utr3_norm$Fus.rep2, minus_utr3_norm$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_utr3_norm$Fus.rep3, minus_utr3_norm$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_utr3_norm$Mbnl1.rep1, minus_utr3_norm$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_utr3_norm$Mbnl1.rep2, minus_utr3_norm$Mbnl1.rep2, paired = F)
Mbnl2 = wilcox.test(plus_utr3_norm$Mbnl2, minus_utr3_norm$Mbnl2, paired = F)
nElavl = wilcox.test(plus_utr3_norm$nElavl, minus_utr3_norm$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_utr3_norm$Ptbp2, minus_utr3_norm$Ptbp2, paired = F)
TD43 = wilcox.test(plus_utr3_norm$TD43, minus_utr3_norm$TD43, paired = F)
Rbfox1 = wilcox.test(plus_utr3_norm$Rbfox1, minus_utr3_norm$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_utr3_norm$Rbfox2, minus_utr3_norm$Rbfox2, paired = F)

# significant change between groups (not normalized by length)
Ago = wilcox.test(plus_utr3$Ago, minus_utr3$Ago, paired = F)
Fus1 = wilcox.test(plus_utr3$Fus.rep1, minus_utr3$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_utr3$Fus.rep2, minus_utr3$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_utr3$Fus.rep3, minus_utr3$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_utr3$Mbnl1.rep1, minus_utr3$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_utr3$Mbnl1.rep2, minus_utr3$Mbnl1.rep2, paired = F)
Mbnl2 = wilcox.test(plus_utr3$Mbnl2, minus_utr3$Mbnl2, paired = F)
nElavl = wilcox.test(plus_utr3$nElavl, minus_utr3$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_utr3$Ptbp2, minus_utr3$Ptbp2, paired = F)
TD43 = wilcox.test(plus_utr3$TD43, minus_utr3$TD43, paired = F)
Rbfox1 = wilcox.test(plus_utr3$Rbfox1, minus_utr3$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_utr3$Rbfox2, minus_utr3$Rbfox2, paired = F)

# CDS
#significant change between groups
Ago = wilcox.test(plus_cds_norm$Ago, minus_cds_norm$Ago, paired = F)
Fus1 = wilcox.test(plus_cds_norm$Fus.rep1, minus_cds_norm$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_cds_norm$Fus.rep2, minus_cds_norm$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_cds_norm$Fus.rep3, minus_cds_norm$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_cds_norm$Mbnl1.rep1, minus_cds_norm$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_cds_norm$Mbnl1.rep2, minus_cds_norm$Mbnl1.rep2, paired = F)
Mbnl2 = 1 # wilcox.test(plus_cds_norm$Mbnl2, minus_cds_norm$Mbnl2, paired = F)
nElavl = wilcox.test(plus_cds_norm$nElavl, minus_cds_norm$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_cds_norm$Ptbp2, minus_cds_norm$Ptbp2, paired = F)
TD43 = wilcox.test(plus_cds_norm$TD43, minus_cds_norm$TD43, paired = F)
Rbfox1 = wilcox.test(plus_cds_norm$Rbfox1, minus_cds_norm$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_cds_norm$Rbfox2, minus_cds_norm$Rbfox2, paired = F)

#significant change between groups
Ago = wilcox.test(plus_cds$Ago, minus_cds$Ago, paired = F)
Fus1 = wilcox.test(plus_cds$Fus.rep1, minus_cds$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_cds$Fus.rep2, minus_cds$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_cds$Fus.rep3, minus_cds$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_cds$Mbnl1.rep1, minus_cds$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_cds$Mbnl1.rep2, minus_cds$Mbnl1.rep2, paired = F)
Mbnl2 = 1 # wilcox.test(plus_cds$Mbnl2, minus_cds$Mbnl2, paired = F)
nElavl = wilcox.test(plus_cds$nElavl, minus_cds$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_cds$Ptbp2, minus_cds$Ptbp2, paired = F)
TD43 = wilcox.test(plus_cds$TD43, minus_cds$TD43, paired = F)
Rbfox1 = wilcox.test(plus_cds$Rbfox1, minus_cds$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_cds$Rbfox2, minus_cds$Rbfox2, paired = F)

# Total
#significant change between groups
Ago = wilcox.test(plus_total_norm$Ago, minus_total_norm$Ago, paired = F)
Fus1 = wilcox.test(plus_total_norm$Fus.rep1, minus_total_norm$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_total_norm$Fus.rep2, minus_total_norm$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_total_norm$Fus.rep3, minus_total_norm$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_total_norm$Mbnl1.rep1, minus_total_norm$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_total_norm$Mbnl1.rep2, minus_total_norm$Mbnl1.rep2, paired = F)
Mbnl2 = wilcox.test(plus_total_norm$Mbnl2, minus_total_norm$Mbnl2, paired = F)
nElavl = wilcox.test(plus_total_norm$nElavl, minus_total_norm$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_total_norm$Ptbp2, minus_total_norm$Ptbp2, paired = F)
TD43 = wilcox.test(plus_total_norm$TD43, minus_total_norm$TD43, paired = F)
Rbfox1 = wilcox.test(plus_total_norm$Rbfox1, minus_total_norm$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_total_norm$Rbfox2, minus_total_norm$Rbfox2, paired = F)

#significant change between groups
Ago = wilcox.test(plus_total$Ago, minus_total$Ago, paired = F)
Fus1 = wilcox.test(plus_total$Fus.rep1, minus_total$Fus.rep1, paired = F)
Fus2 = wilcox.test(plus_total$Fus.rep2, minus_total$Fus.rep2, paired = F)
Fus3 = wilcox.test(plus_total$Fus.rep3, minus_total$Fus.rep3, paired = F)
Mbnl1 = wilcox.test(plus_total$Mbnl1.rep1, minus_total$Mbnl1.rep1, paired = F)
Mbnl1.2 = wilcox.test(plus_total$Mbnl1.rep2, minus_total$Mbnl1.rep2, paired = F)
Mbnl2 = wilcox.test(plus_total$Mbnl2, minus_total$Mbnl2, paired = F)
nElavl = wilcox.test(plus_total$nElavl, minus_total$nElavl, paired = F)
Ptbp2 = wilcox.test(plus_total$Ptbp2, minus_total$Ptbp2, paired = F)
TD43 = wilcox.test(plus_total$TD43, minus_total$TD43, paired = F)
Rbfox1 = wilcox.test(plus_total$Rbfox1, minus_total$Rbfox1, paired = F)
Rbfox2 = wilcox.test(plus_total$Rbfox2, minus_total$Rbfox2, paired = F)



silac_utr3[is.na(silac_utr3)]<-0
silac_utr5[is.na(silac_utr5)]<-0
silac_cds[is.na(silac_cds)]<-0
silac_total[is.na(silac_total)]<-0

write.table(silac_utr3,'clip_peaks_in_utr3_of_silac_targets.txt', sep = '\t', quote = F, row.names=F)
write.table(silac_utr5,'clip_peaks_in_utr5_of_silac_targets.txt', sep = '\t', quote = F, row.names=F)
write.table(silac_cds,'clip_peaks_in_cds_of_silac_targets.txt', sep = '\t', quote = F, row.names=F)
write.table(silac_total,'clip_peaks_in_total_of_silac_targets.txt', sep = '\t', quote = F, row.names=F)

# fisher test
# absolut data
fisher.test(matrix(c(sum(plus_cds$Ago,na.rm=T), sum(minus_cds$Ago,na.rm=T), sum(plus_utr3$Ago,na.rm = T),sum( minus_utr3$Ago,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Fus.rep1,na.rm=T), sum(minus_cds$Fus.rep1,na.rm=T), sum(plus_utr3$Fus.rep1,na.rm = T),sum( minus_utr3$Fus.rep1,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Fus.rep2,na.rm=T), sum(minus_cds$Fus.rep2,na.rm=T), sum(plus_utr3$Fus.rep2,na.rm = T),sum( minus_utr3$Fus.rep2,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Fus.rep3,na.rm=T), sum(minus_cds$Fus.rep3,na.rm=T), sum(plus_utr3$Fus.rep3,na.rm = T),sum( minus_utr3$Fus.rep3,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Mbnl1.rep1,na.rm=T), sum(minus_cds$Mbnl1.rep1,na.rm=T), sum(plus_utr3$Mbnl1.rep1,na.rm = T),sum( minus_utr3$Mbnl1.rep1,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Mbnl1.rep2,na.rm=T), sum(minus_cds$Mbnl1.rep2,na.rm=T), sum(plus_utr3$Mbnl1.rep2,na.rm = T),sum( minus_utr3$Mbnl1.rep2,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Mbnl2,na.rm=T), sum(minus_cds$Mbnl2,na.rm=T), sum(plus_utr3$Mbnl2,na.rm = T),sum( minus_utr3$Mbnl2,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$nElavl,na.rm=T), sum(minus_cds$nElavl,na.rm=T), sum(plus_utr3$nElavl,na.rm = T),sum( minus_utr3$nElavl,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Ptbp2,na.rm=T), sum(minus_cds$Ptbp2,na.rm=T), sum(plus_utr3$Ptbp2,na.rm = T),sum( minus_utr3$Ptbp2,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$TD43,na.rm=T), sum(minus_cds$TD43,na.rm=T), sum(plus_utr3$TD43,na.rm = T),sum( minus_utr3$TD43,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Rbfox1,na.rm=T), sum(minus_cds$Rbfox1,na.rm=T), sum(plus_utr3$Rbfox1,na.rm = T),sum( minus_utr3$Rbfox1,na.rm = T)), ncol = 2))
fisher.test(matrix(c(sum(plus_cds$Rbfox2,na.rm=T), sum(minus_cds$Rbfox2,na.rm=T), sum(plus_utr3$Rbfox2,na.rm = T),sum( minus_utr3$Rbfox2,na.rm = T)), ncol = 2))

# normalized data
fisher.test(matrix(round(c(sum(plus_cds_norm$Ago,na.rm=T), sum(minus_cds_norm$Ago,na.rm=T), sum(plus_utr3_norm$Ago,na.rm = T),sum( minus_utr3_norm$Ago,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Fus.rep1,na.rm=T), sum(minus_cds_norm$Fus.rep1,na.rm=T), sum(plus_utr3_norm$Fus.rep1,na.rm = T),sum( minus_utr3_norm$Fus.rep1,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Fus.rep2,na.rm=T), sum(minus_cds_norm$Fus.rep2,na.rm=T), sum(plus_utr3_norm$Fus.rep2,na.rm = T),sum( minus_utr3_norm$Fus.rep2,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Fus.rep3,na.rm=T), sum(minus_cds_norm$Fus.rep3,na.rm=T), sum(plus_utr3_norm$Fus.rep3,na.rm = T),sum( minus_utr3_norm$Fus.rep3,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Mbnl1.rep1,na.rm=T), sum(minus_cds_norm$Mbnl1.rep1,na.rm=T), sum(plus_utr3_norm$Mbnl1.rep1,na.rm = T),sum( minus_utr3_norm$Mbnl1.rep1,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Mbnl1.rep2,na.rm=T), sum(minus_cds_norm$Mbnl1.rep2,na.rm=T), sum(plus_utr3_norm$Mbnl1.rep2,na.rm = T),sum( minus_utr3_norm$Mbnl1.rep2,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Mbnl2,na.rm=T), sum(minus_cds_norm$Mbnl2,na.rm=T), sum(plus_utr3_norm$Mbnl2,na.rm = T),sum( minus_utr3_norm$Mbnl2,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$nElavl,na.rm=T), sum(minus_cds_norm$nElavl,na.rm=T), sum(plus_utr3_norm$nElavl,na.rm = T),sum( minus_utr3_norm$nElavl,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Ptbp2,na.rm=T), sum(minus_cds_norm$Ptbp2,na.rm=T), sum(plus_utr3_norm$Ptbp2,na.rm = T),sum( minus_utr3_norm$Ptbp2,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$TD43,na.rm=T), sum(minus_cds_norm$TD43,na.rm=T), sum(plus_utr3_norm$TD43,na.rm = T),sum( minus_utr3_norm$TD43,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Rbfox1,na.rm=T), sum(minus_cds_norm$Rbfox1,na.rm=T), sum(plus_utr3_norm$Rbfox1,na.rm = T),sum( minus_utr3_norm$Rbfox1,na.rm = T))*1000), ncol = 2))
fisher.test(matrix(round(c(sum(plus_cds_norm$Rbfox2,na.rm=T), sum(minus_cds_norm$Rbfox2,na.rm=T), sum(plus_utr3_norm$Rbfox2,na.rm = T),sum( minus_utr3_norm$Rbfox2,na.rm = T))*1000), ncol = 2))
